[project]
name = "eda-agent-gemini"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "chainlit",
    "langchain",
    "langgraph",
    "langchain-google-genai",
    "pandas",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
]
